version: '3'

services:
  nginxserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./dist:/var/www
    ports:
      - "80:80"
