# This is a test to make run an simple static website on a ngnix server

version: 2
# First Creating a default Google Cloud Service SDK
defaults: &defaults
  docker:
    - image: google/cloud-sdk@sha256:126a49cfa2aa6e20d561fa14999bf657bc341efeba04939bd2f612bf843d12a6
jobs:
  install:
    docker:
      - image: nginx:stable-alpine
